### ISSUE TITLE
Moving the csv file into a dropbox

### ISSUE THREAD

**Issue by LucieContamin** [epix-project/gso#41]
To avoid trouble with the CI (Continuous Integration), it would be great if we can move all the `.csv` file in the `data-raw` folder into a Dropbox or another GitHub repository. 
But, if we do that, we will have to add a message in the protocol script `update_protocole.R` to indicate where the raw data are and how to download them (for reproducibility).

**Comment by choisy** [comment]
Addressed in pull request #42
